spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC         #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                     #数据库连接池的最小维持连接数
      initial-size: 5                                 #初始化链接数
      max-total: 5                                    #最大连接数
      max-wait-millis: 200                            #等待链接获取的最大超过时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.cloud.pojo                #所有Entity别名类所在路径
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml               #mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: dept-8001.com #服务名称的修改
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: microservicecloud
  company.name: www.starAndcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC         #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                     #数据库连接池的最小维持连接数
      initial-size: 5                                 #初始化链接数
      max-total: 5                                    #最大连接数
      max-wait-millis: 200                            #等待链接获取的最大超过时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.cloud.pojo                #所有Entity别名类所在路径
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml               #mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: dept-8001.com #服务名称的修改
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: microservicecloud
  company.name: www.starAndcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
